### ISSUE TITLE
Impossible to delete post if someone favorites it

### ISSUE THREAD

**Issue by erka** [davecheney/pub#13]
Hey Dave! 👋

There is the issue with deleting a post if someone favorites the post because of database constraint.

```
pub/mastodon/statuses.go:166 Error 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`pub`.`reactions`, CONSTRAINT `fk_statuses_reaction` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`))
[11.669ms] [rows:0] DELETE FROM `statuses` WHERE `statuses`.`id` = '109705640622196888'
HTTP: path: /api/v1/statuses/109705640622196888, status: 500, error: Error 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`pub`.`reactions`, CONSTRAINT `fk_statuses_reaction` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`))
```

Steps to reproduce:
1. create a fresh instance, user and a post,
2. favorite your own post,
3. try to delete the post,
4. observe the behaviour. 

Also it's a bit unclear what happens if you unfavorite the post too.  The deletion process still fails.

**Comment by davecheney** [comment]
Thanks for the report. I’ve noticed a similar problem with statuses that have been rebloged. I hoped that delete constraints would solve this, but I might have been expecting too much. I’ll look into it shortly

**Comment by davecheney** [comment]
> Also it's a bit unclear what happens if you unfavorite the post too. The deletion process still fails.

The root cause is the fk relationship between the `reactions` table and the status.
