### ISSUE TITLE
bcrypt error during instance set-up

### ISSUE THREAD

**Issue by xxxserxxx** [davecheney/pub#15]
Following the instructions, having gotten past the DB setup and in the instance set-up:

```
./pub --dsn 'pub:pub@/pub' create-instance --domain my.domain.com --title "My Instance Title" --description "My instance description" --admin-email my@email.com
pub: error: bcrypt: password length exceeds 72 bytes
```

That's all the information it provides. From a quick glance at the code, none of the password generation is derived from user input.

OS is Linux   
Go is 1.20  
Arch is x86_64

**Comment by davecheney** [comment]
Yup; that's the password we generate for the admin service account. Turns out I thought I was being very clever using the accounts private key as the input to bcrypt, but I have to be more careful that its < 72 bytes.

Fix coming asap.

**Comment by xxxserxxx** [comment]
Confirmed.
