### ISSUE TITLE
.well-known/nodeinfo is not served with the "right" function

### ISSUE THREAD

**Issue by diligiant** [davecheney/pub#17]
Hi,

I noticed what is probably a completion typo at serve.go:177
`r.Get("/nodeinfo", httpx.HandlerFunc(envFn, wellknown.NodeInfoShow))`
which should be instead
`r.Get("/nodeinfo", httpx.HandlerFunc(envFn, wellknown.NodeInfoIndex))`

**Comment by davecheney** [comment]
Thanks for spotting that, fixed
