### ISSUE TITLE
example.org/@user route is missing (account url)

### ISSUE THREAD

**Issue by diligiant** [davecheney/pub#21]
adding `r.Get("/@{name}", httpx.HandlerFunc(envFn, activitypub.UsersShow))` below the `r.Route("/u/{name}"` block fixes that (nginx config needs a new location too.)

**Comment by davecheney** [comment]
Thank you, I haven’t decided what to do about a web viewable version of an account. 

I know that mastodon does the opposite, redirects the activitypub url to the html version. 

I think at some point I’ll add a html view of the profile and statusss, but it’s not intended to be a full ui, pub’s main goal is to be a bridge between activitypub and the mastodon api

**Comment by diligiant** [comment]
It wasn't about "html" but fully implementing the aliases that you declare in webfinger.

BTW, if you set "Accept: application/activity+json" on the masto server on those urls, it shows the "right" thing (ie same as you).

I got there when I dug regarding search => querying any alias URL brings back json with the correct "canonical" id (activitypub uri).

**Comment by davecheney** [comment]
excellent point. I make pub's webfinger duplicate what mastodon did. Perhaps the correct approach is to stop advertising in webfinger the parts that aren't implemented.

**Comment by davecheney** [comment]
@diligiant please let me know what you think.

**Comment by diligiant** [comment]
Well, I'd do that and handle it anyway!

Apps can't prevent users from searching https://domain.org/@user. That's not the ActPub URI but it's easier to grasp. By responding, "whoever" does the query will be able to get the ActPub URI in "id".
