### ISSUE TITLE
Typo in import command

### ISSUE THREAD

**Issue by erka** [davecheney/pub#9]
Hey! 👋

I believe there is typo in `import` command name. Currently it's `imoport` per https://github.com/davecheney/pub/blob/main/main.go#L31

```
❯ pub import
pub: error: unexpected argument import, did you mean "imoport"?
```

**Comment by davecheney** [comment]
Thanks for spotting that; tbh I don’t think I finished that command, it was mostly for bootstrapping my test instance every time I nuked the db. 

I’ll review that command and nuke it if it’s atrophied.
